//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bookstore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;xsl:stylesheet version=&quot;1.0&quot;
        ///xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;body&gt;
        ///        &lt;h2&gt;My Books&lt;/h2&gt;
        ///        &lt;table border=&quot;1&quot;&gt;
        ///          &lt;tr&gt;
        ///            &lt;th&gt;Title&lt;/th&gt;
        ///            &lt;th&gt;Author&lt;/th&gt;
        ///            &lt;th&gt;Category&lt;/th&gt;
        ///            &lt;th&gt;Year&lt;/th&gt;
        ///            &lt;th&gt;Price&lt;/th&gt;
        ///          &lt;/tr&gt;
        ///          &lt;xsl:for-each select=&quot;bookstore/book&quot;&gt;
        ///            &lt;tr&gt;
        ///              &lt;td&gt;
        ///              [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string books {
            get {
                return ResourceManager.GetString("books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ru Русский
        ///ab Абхазский
        ///av Аварский
        ///ae Авестийский
        ///az Азербайджанский
        ///ay Аймара
        ///ak Акан
        ///sq Албанский
        ///am Амхарский
        ///en Английский
        ///ar Арабский
        ///hy Армянский
        ///as Ассамский
        ///aa Афарский
        ///af Африкаанс
        ///bm Бамбара
        ///eu Баскский
        ///ba Башкирский
        ///be Белорусский
        ///bn Бенгальский
        ///my Бирманский
        ///bi Бислама
        ///bg Болгарский
        ///bs Боснийский
        ///br Бретонский
        ///cy Валлийский
        ///hu Венгерский
        ///ve Венда
        ///vo Волапюк
        ///wo Волоф
        ///vi Вьетнамский
        ///gl Галисийский
        ///lg Ганда
        ///hz Гереро
        ///kl Гренландский
        ///el Греческий
        ///ka Грузинский
        ///g [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
    }
}
